module.exports = {
    data: () => ({
        nationality: [
            {value: null, text: '(Selected Nationality)'},
            {value: 'AF', text: 'Afghan'},
            {value: 'AX', text: 'Aland Island'},
            {value: 'AL', text: 'Albanian'},
            {value: 'DZ', text: 'Algerian'},
            {value: 'AS', text: 'American Samoan'},
            {value: 'AD', text: 'Andorran'},
            {value: 'AO', text: 'Angolan'},
            {value: 'AI', text: 'Anguillan'},
            {value: 'AQ', text: 'Antarctic'},
            {value: 'AG', text: 'Antiguan or Barbudan'},
            {value: 'AR', text: 'Argentine'},
            {value: 'AM', text: 'Armenian'},
            {value: 'AW', text: 'Aruban'},
            {value: 'AU', text: 'Australian'},
            {value: 'AT', text: 'Austrian'},
            {value: 'AZ', text: 'Azerbaijani, Azeri'},
            {value: 'BS', text: 'Bahamian'},
            {value: 'BH', text: 'Bahraini'},
            {value: 'BD', text: 'Bangladeshi'},
            {value: 'BB', text: 'Barbadian'},
            {value: 'BY', text: 'Belarusian'},
            {value: 'BE', text: 'Belgian'},
            {value: 'BZ', text: 'Belizean'},
            {value: 'BJ', text: 'Beninese, Beninois'},
            {value: 'BM', text: 'Bermudian, Bermudan'},
            {value: 'BT', text: 'Bhutanese'},
            {value: 'BO', text: 'Bolivian'},
            {value: 'BQ', text: 'Bonaire'},
            {value: 'BA', text: 'Bosnian or Herzegovinian'},
            {value: 'BW', text: 'Motswana, Botswanan'},
            {value: 'BV', text: 'Bouvet Island'},
            {value: 'BR', text: 'Brazilian'},
            {value: 'IO', text: 'BIOT'},
            {value: 'BN', text: 'Bruneian'},
            {value: 'BG', text: 'Bulgarian'},
            {value: 'BF', text: 'Burkina Faso'},
            {value: 'BI', text: 'Burundian'},
            {value: 'CV', text: 'Cabo Verdean'},
            {value: 'KH', text: 'Cambodian'},
            {value: 'CM', text: 'Cameroonian'},
            {value: 'CA', text: 'Canadian'},
            {value: 'KY', text: 'Caymanian'},
            {value: 'CF', text: 'Central African'},
            {value: 'TD', text: 'Chadian'},
            {value: 'CL', text: 'Chilean'},
            {value: 'CN', text: 'Chinese'},
            {value: 'CX', text: 'Christmas Island'},
            {value: 'CC', text: 'Cocos Island'},
            {value: 'CO', text: 'Colombian'},
            {value: 'KM', text: 'Comoran, Comorian'},
            {value: 'CG', text: 'Congolese'},
            {value: 'CD', text: 'Congolese'},
            {value: 'CK', text: 'Cook Island'},
            {value: 'CR', text: 'Costa Rican'},
            {value: 'CI', text: 'Ivorian'},
            {value: 'HR', text: 'Croatian'},
            {value: 'CU', text: 'Cuban'},
            {value: 'CW', text: 'Curaçao'},
            {value: 'CY', text: 'Cypriot'},
            {value: 'CZ', text: 'Czech'},
            {value: 'DK', text: 'Danish'},
            {value: 'DJ', text: 'Djiboutian'},
            {value: 'DM', text: 'Dominican'},
            {value: 'DO', text: 'Dominican'},
            {value: 'EC', text: 'Ecuadorian'},
            {value: 'EG', text: 'Egyptian'},
            {value: 'SV', text: 'Salvadoran'},
            {value: 'GQ', text: 'Equatorial Guinean, Equatoguinean'},
            {value: 'ER', text: 'Eritrean'},
            {value: 'EE', text: 'Estonian'},
            {value: 'ET', text: 'Ethiopian'},
            {value: 'FK', text: 'Falkland Island'},
            {value: 'FO', text: 'Faroese'},
            {value: 'FJ', text: 'Fijian'},
            {value: 'FI', text: 'Finnish'},
            {value: 'FR', text: 'French'},
            {value: 'GF', text: 'French Guianese'},
            {value: 'PF', text: 'French Polynesian'},
            {value: 'TF', text: 'French Southern Territories'},
            {value: 'GA', text: 'Gabonese'},
            {value: 'GM', text: 'Gambian'},
            {value: 'GE', text: 'Georgian'},
            {value: 'DE', text: 'German'},
            {value: 'GH', text: 'Ghanaian'},
            {value: 'GI', text: 'Gibraltar'},
            {value: 'GR', text: 'Greek, Hellenic'},
            {value: 'GL', text: 'Greenlandic'},
            {value: 'GD', text: 'Grenadian'},
            {value: 'GP', text: 'Guadeloupe'},
            {value: 'GU', text: 'Guamanian, Guambat'},
            {value: 'GT', text: 'Guatemalan'},
            {value: 'GG', text: 'Channel Island'},
            {value: 'GN', text: 'Guinean'},
            {value: 'GW', text: 'Bissau-Guinean'},
            {value: 'GY', text: 'Guyanese'},
            {value: 'HT', text: 'Haitian'},
            {value: 'HM', text: 'Heard Island or McDonald Islands'},
            {value: 'VA', text: 'Vatican'},
            {value: 'HN', text: 'Honduran'},
            {value: 'HK', text: 'Hong Kong, Hong Kongese'},
            {value: 'HU', text: 'Hungarian, Magyar'},
            {value: 'IS', text: 'Icelandic'},
            {value: 'IN', text: 'Indian'},
            {value: 'ID', text: 'Indonesian'},
            {value: 'IR', text: 'Iranian, Persian'},
            {value: 'IQ', text: 'Iraqi'},
            {value: 'IE', text: 'Irish'},
            {value: 'IM', text: 'Manx'},
            {value: 'IL', text: 'Israeli'},
            {value: 'IT', text: 'Italian'},
            {value: 'JM', text: 'Jamaican'},
            {value: 'JP', text: 'Japanese'},
            {value: 'JE', text: 'Channel Island'},
            {value: 'JO', text: 'Jordanian'},
            {value: 'KZ', text: 'Kazakhstani, Kazakh'},
            {value: 'KE', text: 'Kenyan'},
            {value: 'KI', text: 'I-Kiribati'},
            {value: 'KP', text: 'North Korean'},
            {value: 'KR', text: 'South Korean'},
            {value: 'KW', text: 'Kuwaiti'},
            {value: 'KG', text: 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz'},
            {value: 'LA', text: 'Lao, Laotian'},
            {value: 'LV', text: 'Latvian'},
            {value: 'LB', text: 'Lebanese'},
            {value: 'LS', text: 'Basotho'},
            {value: 'LR', text: 'Liberian'},
            {value: 'LY', text: 'Libyan'},
            {value: 'LI', text: 'Liechtenstein'},
            {value: 'LT', text: 'Lithuanian'},
            {value: 'LU', text: 'Luxembourg, Luxembourgish'},
            {value: 'MO', text: 'Macanese, Chinese'},
            {value: 'MK', text: 'Macedonian'},
            {value: 'MG', text: 'Malagasy'},
            {value: 'MW', text: 'Malawian'},
            {value: 'MY', text: 'Malaysian'},
            {value: 'MV', text: 'Maldivian'},
            {value: 'ML', text: 'Malian, Malinese'},
            {value: 'MT', text: 'Maltese'},
            {value: 'MH', text: 'Marshallese'},
            {value: 'MQ', text: 'Martiniquais, Martinican'},
            {value: 'MR', text: 'Mauritanian'},
            {value: 'MU', text: 'Mauritian'},
            {value: 'YT', text: 'Mahoran'},
            {value: 'MX', text: 'Mexican'},
            {value: 'FM', text: 'Micronesian'},
            {value: 'MD', text: 'Moldovan'},
            {value: 'MC', text: 'Monacan'},
            {value: 'MN', text: 'Mongolian'},
            {value: 'ME', text: 'Montenegrin'},
            {value: 'MS', text: 'Montserratian'},
            {value: 'MA', text: 'Moroccan'},
            {value: 'MZ', text: 'Mozambican'},
            {value: 'MM', text: 'Burmese'},
            {value: 'NA', text: 'Namibian'},
            {value: 'NR', text: 'Nauruan'},
            {value: 'NP', text: 'Nepali, Nepalese'},
            {value: 'NL', text: 'Dutch, Netherlandic'},
            {value: 'NC', text: 'New Caledonian'},
            {value: 'NZ', text: 'New Zealand, NZ'},
            {value: 'NI', text: 'Nicaraguan'},
            {value: 'NE', text: 'Nigerien'},
            {value: 'NG', text: 'Nigerian'},
            {value: 'NU', text: 'Niuean'},
            {value: 'NF', text: 'Norfolk Island'},
            {value: 'MP', text: 'Northern Marianan'},
            {value: 'NO', text: 'Norwegian'},
            {value: 'OM', text: 'Omani'},
            {value: 'PK', text: 'Pakistani'},
            {value: 'PW', text: 'Palauan'},
            {value: 'PS', text: 'Palestinian'},
            {value: 'PA', text: 'Panamanian'},
            {value: 'PG', text: 'Papua New Guinean, Papuan'},
            {value: 'PY', text: 'Paraguayan'},
            {value: 'PE', text: 'Peruvian'},
            {value: 'PH', text: 'Philippine, Filipino'},
            {value: 'PN', text: 'Pitcairn Island'},
            {value: 'PL', text: 'Polish'},
            {value: 'PT', text: 'Portuguese'},
            {value: 'PR', text: 'Puerto Rican'},
            {value: 'QA', text: 'Qatari'},
            {value: 'RO', text: 'Romanian'},
            {value: 'RU', text: 'Russian'},
            {value: 'RW', text: 'Rwandan'},
            {value: 'SH', text: 'Saint Helenian'},
            {value: 'KN', text: 'Kittitian or Nevisian'},
            {value: 'LC', text: 'Saint Lucian'},
            {value: 'MF', text: 'Saint-Martinoise'},
            {value: 'PM', text: 'Saint-Pierrais or Miquelonnais'},
            {value: 'VC', text: 'Saint Vincentian, Vincentian'},
            {value: 'WS', text: 'Samoan'},
            {value: 'SM', text: 'Sammarinese'},
            {value: 'SA', text: 'Saudi, Saudi Arabian'},
            {value: 'SN', text: 'Senegalese'},
            {value: 'RS', text: 'Serbian'},
            {value: 'SC', text: 'Seychellois'},
            {value: 'SL', text: 'Sierra Leonean'},
            {value: 'SG', text: 'Singaporean'},
            {value: 'SX', text: 'Sint Maarten'},
            {value: 'SK', text: 'Slovak'},
            {value: 'SI', text: 'Slovenian, Slovene'},
            {value: 'SB', text: 'Solomon Island'},
            {value: 'SO', text: 'Somali, Somalian'},
            {value: 'ZA', text: 'South African'},
            {value: 'GS', text: 'South Georgia or South Sandwich Islands'},
            {value: 'SS', text: 'South Sudanese'},
            {value: 'ES', text: 'Spanish'},
            {value: 'LK', text: 'Sri Lankan'},
            {value: 'SD', text: 'Sudanese'},
            {value: 'SR', text: 'Surinamese'},
            {value: 'SJ', text: 'Svalbard'},
            {value: 'SZ', text: 'Swazi'},
            {value: 'SE', text: 'Swedish'},
            {value: 'CH', text: 'Swiss'},
            {value: 'SY', text: 'Syrian'},
            {value: 'TW', text: 'Chinese, Taiwanese'},
            {value: 'TJ', text: 'Tajikistani'},
            {value: 'TZ', text: 'Tanzanian'},
            {value: 'TH', text: 'Thai'},
            {value: 'TL', text: 'Timorese'},
            {value: 'TG', text: 'Togolese'},
            {value: 'TK', text: 'Tokelauan'},
            {value: 'TO', text: 'Tongan'},
            {value: 'TT', text: 'Trinidadian or Tobagonian'},
            {value: 'TN', text: 'Tunisian'},
            {value: 'TR', text: 'Turkish'},
            {value: 'TM', text: 'Turkmen'},
            {value: 'TC', text: 'Turks and Caicos Island'},
            {value: 'TV', text: 'Tuvaluan'},
            {value: 'UG', text: 'Ugandan'},
            {value: 'UA', text: 'Ukrainian'},
            {value: 'AE', text: 'Emirati, Emirian, Emiri'},
            {value: 'GB', text: 'British, UK'},
            {value: 'UM', text: 'American'},
            {value: 'US', text: 'American'},
            {value: 'UY', text: 'Uruguayan'},
            {value: 'UZ', text: 'Uzbekistani, Uzbek'},
            {value: 'VU', text: 'Ni-Vanuatu, Vanuatuan'},
            {value: 'VE', text: 'Venezuelan'},
            {value: 'VN', text: 'Vietnamese'},
            {value: 'VG', text: 'British Virgin Island'},
            {value: 'VI', text: 'U.S. Virgin Island'},
            {value: 'WF', text: 'Wallis and Futuna, Wallisian or Futunan'},
            {value: 'EH', text: 'Sahrawi, Sahrawian, Sahraouian'},
            {value: 'YE', text: 'Yemeni'},
            {value: 'ZM', text: 'Zambian'},
            {value: 'ZW', text: 'Zimbabwean'}
        ]
    })
};